#!/usr/bin/env bash

latest_oracle_jdk() {
    local X Xversion Xmajor Xminor Xhome
    for X in /Library/Java/JavaVirtualMachines/jdk*.jdk
    do
        # com.oracle.java.7u25.jdk
        Xversion="$(defaults read "${X}/Contents/Info" CFBundleIdentifier)"
        Xversion="${Xid#com.oracle.java.*}"
        Xversion="${Xid%*.jdk}" # 7u25
        Xmajor="${Xid%u*}"
        Xminor="${Xid#*u}"
        Xhome="${X}/Contents/Home"
        [ -d "$Xhome" ] && \
        [ ! -z "$Xmajor" ] && \
        [ ! -z "$Xminor" ] && \
            printf "%08i%08i:%s\n" "$Xmajor" "$Xminor" "$Xhome"
    done | sort -r | head -n 1 | cut -d: -f2 
}

JAVA_HOME="$(latest_oracle_jdk)"
if [ -z "$JAVA_HOME" ] || [ ! -d "$JAVA_HOME" ]
then
	JAVA_HOME='/System/Library/Frameworks/JavaVM.framework/Versions/CurrentJDK/Home'
fi

export JAVA_HOME
export PATH="${PATH}:${JAVA_HOME}/bin"
