#!/usr/bin/env bash
export ANDROID_HOME="/Applications/Android Studio.app/sdk" \
       ANDROID_NDK_HOME="${HOME}/.prefix/opt/android-ndk" \
       PATH="$PATH:${ANDROID_HOME}/platform-tools:${ANDROID_HOME}/tools:${ANDROID_NDK_HOME}"


