#!/bin/bash

function check_install_source_highlight() {
	if ! which source-highlight >/dev/null 2>&1
	then
		echo -e "\033[01;33mWARNING:\033[0m source-highlight was not found. To install it,"
		if ! which port >/dev/null 2>&1
		then
			echo "first install macports, then:"
		fi
		echo "    sudo port install source-highlight"
		echo
		return 1
	fi
}

function check_install_source_highlight_lesspipe_style() {
	if [ ! -f "${HOME}/.source-highlight/lesspipe.style" ]
	then
		mkdir -p "${HOME}/.source-highlight" && \
		cat >"${HOME}/.source-highlight/lesspipe.style" <<-EOT
		keyword blue b;
		type, classname darkgreen;
		string red;
		regexp orange;
		specialchar pink;
		comment cyan i;
		number purple;
		preproc darkblue b;
		symbol darkred;
		function white b;
		cbracket red;
		variable darkgreen;
		
		// line numbers
		linenum yellow;
		
		// other elements for ChangeLog and Log files
		date blue;
		time darkblue;
		ip darkgreen;
		file darkblue;
		name darkgreen;
		
		// Internet related
		url blue u;
		
		// for diffs
		oldfile orange;
		newfile darkgreen;
		difflines blue;
		
		// for css
		selector purple;
		property blue;
		value darkgreen i;
		EOT
	fi
	if [ ! -r "${HOME}/.source-highlight/lesspipe.style" ]
	then
		chmod 600 "${HOME}/.source-highlight/lesspipe.style"
	fi
}

function check_install_source_highlight_lesspipe_sh() {
	if [ ! -r "${HOME}/.source-highlight/lesspipe.sh" ]
	then
		mkdir -p "${HOME}/.source-highlight" && \
		cat >"${HOME}/.source-highlight/lesspipe.sh" <<-EOT
		#! /bin/sh
		for x
		do
			case "\$x" in
				*ChangeLog|*changelog)
					o='--lang-def=changelog.lang';;
				*Makefile|*makefile)
					o='--lang-def=makefile.lang';;
				*)
					o='--infer-lang';;
			esac
			source-highlight --failsafe -f esc \$o --style-file="${HOME}/.source-highlight/lesspipe.style" -i "\$x"
		done
		EOT
	fi
	if [ ! -x "${HOME}/.source-highlight/lesspipe.sh" ]
	then
		chmod 700 "${HOME}/.source-highlight/lesspipe.sh"
	fi
}

# add some colors to man pages
export LESS_TERMCAP_us=$'\E[01;32m' LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_md=$'\e[01m'    LESS_TERMCAP_me=$'\e[0m'
export LESS='-FXN'

# …and then add some to other files as well
if check_install_source_highlight
then
	check_install_source_highlight_lesspipe_style && \
	check_install_source_highlight_lesspipe_sh && \
	export LESSOPEN="| '${HOME}/.source-highlight/lesspipe.sh' %s" LESS=${LESS}' -R' || \
	echo -e "\033[01;33mWARNING:\033[0m Couldn't install source-highlight script for less in ~/.source-highlight"
fi

unset check_install_source_highlight check_install_source_highlight_lesspipe_style check_install_source_highlight_lesspipe_sh
