#!/usr/bin/env bash

# save multiline commands in history
shopt -s cmdhist

# bind PgUp/PgDn
bind '"\e[5~": history-search-backward'
bind '"\e[6~": history-search-forward'

# disable logging for argument-less ls and cd, pwd, exit, fg, bg…
export HISTIGNORE="&:ls:cd:pwd:[bf]g:exit"

# erase duplicates of the last line
export HISTCONTROL="erasedups"

