#!/usr/bin/env bash

if [ -f "${HOME}/.gitauthor" ]
then
	while true
	do
		read GIT_AUTHOR_NAME
		read GIT_AUTHOR_EMAIL
		break
	done < "${HOME}/.gitauthor"
	[ -z "$GIT_AUTHOR_NAME" ] || [ -z "$GIT_AUTHOR_EMAIL" ] || \
	export GIT_AUTHOR_NAME GIT_AUTHOR_EMAIL GIT_COMMITTER_NAME="$GIT_AUTHOR_NAME" GIT_COMMITTER_EMAIL="$GIT_AUTHOR_EMAIL"
fi

