#!/bin/bash -e -u -o pipefail

printf '  Show filename extensions…\n'
defaults write -g AppleShowAllExtensions -bool true

printf '  Reveal the ~/Library folder…\n'
chflags nohidden "$HOME/Library"

printf '  Set fast key repeat rate…\n'
defaults write -g KeyRepeat -int 0

printf '  Enable tap-to-click for the current user and in the login screen…\n'
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
defaults -currentHost write -g com.apple.mouse.tapBehavior -int 1
defaults write -g com.apple.mouse.tapBehavior -int 1

printf '  Enable subpixel font rendering on non-Apple screens…\n'
defaults write -g AppleFontSmoothing -int 2

printf '  Disable "natural" scrolling…\n'
defaults write -g com.apple.swipescrolldirection -bool false

printf '  Disable rubber-band scrolling…\n'
defaults write -g NSScrollViewRubberbanding -bool false

printf '  Disable "resume" in apps…\n'
defaults write -g NSQuitAlwaysKeepsWindows -bool false

printf '  Disable automatic termination of inactive apps…\n'
defaults write -g NSDisableAutomaticTermination -bool true
