#!/bin/bash -e -u -o pipefail

link-dotfile() {
	delete-if-exists "$HOME/$1"
	ln -s "$DOTFILES_DIR/$1" "$HOME/$1"
}

printf '  Cloning configuration repo…\n'
delete-if-exists "$DOTFILES_DIR"
git clone "git@github.com:${DOTFILES_REPO}.git" "$DOTFILES_DIR"

printf '  Pulling submodules…\n'
git -C "$DOTFILES_DIR" submodule update --init --recursive --force

printf '  Linking files…\n'
link-dotfile .bash.d
link-dotfile .bash_profile
link-dotfile .gitconfig
link-dotfile .gitconfig.d
link-dotfile .inputrc
link-dotfile .vim
link-dotfile .vimrc
