#!/bin/bash -e -u -o pipefail

link-dotfile() {
	ln -sf "$DOTFILES_DIR/$1" "$HOME/$1"
}

[ -d "$DOTFILES_DIR" ] || {
	printf '  Cloning configuration repo…\n'
	git clone 'git@github.com:jcayzac/dotfiles.git' "$DOTFILES_DIR"
}

printf '  Pulling submodules…\n'
git -C "$DOTFILES_DIR" submodule update --init --recursive --force

printf '  Linking files…\n'
link-dotfile .bash.d
link-dotfile .bash_profile
link-dotfile .gitconfig
link-dotfile .gitconfig.d
link-dotfile .inputrc
link-dotfile .vim
link-dotfile .vimrc
