#!/bin/bash -e -u -o pipefail
declare HOMEBREW_API_TOKEN_ENC="homebrew-api-token.txe"

printf '  Decrypting API token…\n'
decrypt -in "bootstrap/$HOMEBREW_API_TOKEN_ENC" -out "$HOME/.HOMEBREW_GITHUB_API_TOKEN"
chmod 600 "$HOME/.HOMEBREW_GITHUB_API_TOKEN"
read -d '' -r HOMEBREW_GITHUB_API_TOKEN <"$HOME/.HOMEBREW_GITHUB_API_TOKEN"
export HOMEBREW_GITHUB_API_TOKEN

download 'homebrew-install.sh' 'https://raw.githubusercontent.com/Homebrew/install/master/install.sh'
printf '  Installing Homebrew…\n'
/bin/bash 'homebrew-install.sh'

cp 'bootstrap/homebrew.packages' 'homebrew.packages'
[ ! -f "bootstrap/homebrew.packages.$PROFILE" ] || {
	echo >>'homebrew.packages'
	cat "bootstrap/homebrew.packages.$PROFILE" >>'homebrew.packages'
}

declare TAPS="$( grep -E '^[^/]+/' <homebrew.packages | cut -d/ -f1-2 | sort -u )"
declare PACKAGES="$( grep -Ev '^(#|homebrew/cask)' <homebrew.packages )"
declare CASKS="$( grep -E '^homebrew/cask' <homebrew.packages )"

for TAP in $TAPS
do
	printf '  Tapping [%s]…\n' "$TAP"
  brew tap -q --shallow "$TAP"
done

printf '  Fetching packages…\n'
brew fetch $PACKAGES

printf '  Fetching casks…\n'
brew cask fetch $CASKS

printf '  Installing packages…\n'
brew install $PACKAGES mas

printf '  Installing casks…\n'
brew cask install $CASKS

printf '  Cleaning up…'
brew cleanup -v -s
