#!/bin/bash -e -u -o pipefail

cp 'bootstrap/mas.packages' 'mas.packages'
[ ! -f "bootstrap/mas.packages.$PROFILE" ] || {
	echo >>'mas.packages'
	cat "bootstrap/mas.packages.$PROFILE" >>'mas.packages'
}

printf '  Installing AppStore apps…\n'
mas install $(grep -Ev '^[[:space:]]*#' <mas.packages | cut -d ' ' -f1)
