#!/bin/bash -e -u -o pipefail
printf '  Installing Volta…\n'
curl -fsSL https://get.volta.sh | bash -s -- --skip-setup

printf '  Install latest version of Node…\n'
export VOLTA_HOME="$HOME/.volta"
export PATH="$VOLTA_HOME/bin:$PATH"
volta install node
