#!/bin/bash -e -u -o pipefail

printf '  Decrypting…\n'
delete-if-exists ".ssh"
decrypt -in "bootstrap/ssh-config.tbe" | tar --no-same-permissions -xvjf -

printf '  Enforcing permissions…\n'
chmod 700 .ssh
chmod 600 .ssh/*
chmod 644 .ssh/*.pub .ssh/known_hosts

printf '  Moving into place…\n'
delete-if-exists "$HOME/.ssh"
mv .ssh "$HOME"/
